export const FORM_FIELDS_LOADING_ACTION = "FORM_FIELDS_LOADING";
export const FORM_FIELDS_SET_ACTION = "FORM_FIELDS_SET";
export const FORM_FIELDS_ERROR_ACTION = "FORM_FIELDS_ERROR";

export const ORDERS_LOADING_ACTION = "ORDERS_LOADING";
export const ORDERS_SET_ACTION = "ORDERS_SET";
export const ORDERS_ERROR_ACTION = "ORDERS_ERROR";

export const DETAIL_LOADING_ACTION = "DETAIL_LOADING";
export const DETAIL_SET_ACTION = "DETAIL_SET";
export const DETAIL_ERROR_ACTION = "DETAIL_ERROR";
export const DETAIL_CLEAR_ACTION = "DETAIL_CLEAR";
